"""Build shipped statistics from sources/.

    python3 tools/pipeline/run.py                 # every source
    python3 tools/pipeline/run.py hmrc ge2024     # just these
    python3 tools/pipeline/run.py --refresh hmrc  # re-download raw files first

Each sources/<id>/ holds source.json (what it is, licence, how to fetch it,
which statistics it yields) and, unless it only supplies geography, build.py
with a build(src) function returning ({stat_id: rows}, {stat_id: [dropped]}).

Writes Play/data/stats/<stat>.csv, Play/data/stats.json (the catalogue the game reads)
and Play/data/stats/README.md (the human-readable licence record). A statistic is
not written unless it passes common.check_stat, and an area that drops out of
a join must be declared in the source's knownGaps or the build fails.
"""
import datetime
import hashlib
import importlib.util
import json
import os
import sys
import zipfile

sys.path.insert(0, os.path.dirname(__file__))
import common  # noqa: E402
from common import BuildError  # noqa: E402

CATALOGUE = os.path.join(common.GAME_DATA, 'stats.json')
README = os.path.join(common.STATS, 'README.md')
REQUIRED = ('id', 'title', 'publisher', 'page', 'vintage', 'refresh', 'licence', 'attribution')


def load_sources():
    out = {}
    for d in sorted(os.listdir(common.SOURCES)):
        p = os.path.join(common.SOURCES, d, 'source.json')
        if os.path.exists(p):
            src = json.load(open(p, encoding='utf-8'))
            missing = [k for k in REQUIRED if not src.get(k)]
            if missing:
                raise BuildError('%s: source.json lacks %s' % (d, ', '.join(missing)))
            if src['id'] != d:
                raise BuildError('%s: id %r does not match its folder' % (d, src['id']))
            out[d] = src
    return out


def fetch_all(src, refresh):
    for f in src.get('fetch', []):
        dest = common.raw_path(src['id'], f['file'])
        if f.get('overpass'):
            print('  fetch %s' % f['file'])
            common.fetch_overpass(f['overpass'], dest, refresh)
        elif f.get('arcgis'):
            print('  fetch %s' % f['file'])
            common.fetch_arcgis(f['arcgis'], dest, f.get('fields', '*'), refresh)
        elif f.get('url'):
            print('  fetch %s' % f['file'])
            common.fetch(f['url'], dest, refresh)
            if f.get('unzip'):
                out = dest[:-4]
                if refresh or not os.path.isdir(out):
                    zipfile.ZipFile(dest).extractall(out)
        elif not os.path.exists(dest):
            raise BuildError('%s: %s must be downloaded by hand. %s'
                             % (src['id'], dest, f.get('manual', '')))


def run_build(src):
    spec = importlib.util.spec_from_file_location(
        'build_' + src['id'], os.path.join(common.SOURCES, src['id'], 'build.py'))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build(src)


def licences_for(src, sources):
    """The source's own licence plus those of every source it draws on
    (e.g. the boundaries that give each point its coordinates)."""
    chain = [src] + [sources[u] for u in src.get('uses', [])]
    lic, attr, seen = [], [], set()
    for s in chain:
        if s['licence']['name'] not in seen:
            seen.add(s['licence']['name'])
            lic.append(s['licence'])
        attr.append(s['attribution'])
    return lic, attr


def catalogue_entry(stat, src, sources, info):
    lic, attr = licences_for(src, sources)
    links = [{'label': '%s — %s' % (src['publisher'], src['title']), 'url': src['page']}]
    for u in src.get('uses', []):
        links.append({'label': sources[u]['title'], 'url': sources[u]['page']})
    return {
        'id': stat['id'], 'label': stat['label'], 'question': stat['question'],
        'unit': stat['unit'], 'family': stat.get('family', src['title']),
        'file': 'stats/%s.csv' % stat['id'], 'source': src['id'],
        'vintage': src['vintage'], 'licences': lic, 'attribution': attr,
        # What the shipped file itself is released under. Defaults to the
        # source's own licence; OSM-derived files must stay ODbL.
        'derivedLicence': src.get('derivedLicence', src['licence']),
        'sources': links, 'caveats': src.get('caveats', []) + stat.get('caveats', [])
                   + list(stat.get('absentFrom', {}).values()),
        'points': info['points'], 'total': info['total'], 'nationShares': info['shares'],
        'built': datetime.date.today().isoformat(),
    }


def write_readme(cat, sources):
    L = ['# Play/data/stats — what each file is, and its licence', '',
         'Generated by `tools/pipeline/run.py`; do not edit by hand. Every file',
         'has the same four columns: `lon,lat,value,name` (WGS84 degrees, the',
         'statistic, and the local authority or constituency the point names).', '',
         'These files are **derived data**. Each section below states the licence',
         'the files themselves are released under, the licences of the sources they',
         'were made from, and the attribution statements any reuse must carry.',
         'Processing by MapSplit',
         '(puntofisso.net) — see `sources/<source>/build.py` for exactly what was',
         'done to each.', '']
    by_src = {}
    for e in cat.values():
        by_src.setdefault(e['source'], []).append(e)
    for sid in sorted(by_src):
        src = sources[sid]
        L += ['## %s — %s' % (src['publisher'], src['title']), '',
              '- Source: %s' % src['page'],
              '- Vintage: %s' % src['vintage'],
              '- Source licences: %s' % '; '.join('[%s](%s)' % (l['name'], l['url'])
                                                  for l in by_src[sid][0]['licences']),
              '- **These derived files are licensed under: %s**%s' % (
                  '[%s](%s)' % (by_src[sid][0]['derivedLicence']['name'], by_src[sid][0]['derivedLicence']['url']),
                  (' — ' + by_src[sid][0]['derivedLicence']['note']) if by_src[sid][0]['derivedLicence'].get('note') else ''),
              '- Attribution:']
        L += ['  - %s' % a for a in by_src[sid][0]['attribution']]
        L += ['', '| File | Statistic | Points | Total |', '| --- | --- | --- | --- |']
        for e in sorted(by_src[sid], key=lambda e: e['id']):
            L.append('| `%s` | %s | %d | %s |' % (e['file'].split('/')[-1], e['label'],
                                                  e['points'], format(round(e['total']), ',')))
        L.append('')
    open(README, 'w', encoding='utf-8').write('\n'.join(L))


def main(argv):
    refresh = '--refresh' in argv
    want = [a for a in argv if not a.startswith('--')]
    sources = load_sources()
    unknown = [w for w in want if w not in sources]
    if unknown:
        raise BuildError('unknown source(s): %s' % ', '.join(unknown))
    todo = want or list(sources)

    cat = json.load(open(CATALOGUE, encoding='utf-8')) if os.path.exists(CATALOGUE) else {}
    for sid in todo:
        src = sources[sid]
        print('%s:' % sid)
        fetch_all(src, refresh)
        if not src.get('stats'):
            continue
        built, dropped = run_build(src)
        declared = {s['id'] for s in src['stats']}
        if set(built) != declared:
            raise BuildError('%s: build produced %s, source.json declares %s'
                             % (sid, sorted(built), sorted(declared)))
        stat_by_id = {s['id']: s for s in src['stats']}
        def gaps_for(st):
            # Source-wide gaps plus any the statistic declares for itself.
            return dict(src.get('knownGaps', {}), **stat_by_id[st].get('knownGaps', {}))
        for st, codes in dropped.items():
            gaps = gaps_for(st)
            surprise = [c for c in codes if c not in gaps]
            if surprise:
                raise BuildError('%s/%s: areas dropped that knownGaps does not explain: %s'
                                 % (sid, st, ', '.join(surprise)))
        for k in [k for k, e in cat.items() if e['source'] == sid]:
            del cat[k]
        # Small areas and individual places are aggregated to local
        # authorities when the source asks for it (Play/data/stats/ was 68 MB at
        # small-area resolution); a statistic can opt out with "aggregate": null.
        for stat in src['stats']:
            how = stat.get('aggregate', src.get('aggregate'))
            if how == 'lad':
                built[stat['id']] = common.aggregate_lad(built[stat['id']])
            elif how:
                raise BuildError('%s: unknown aggregate %r' % (stat['id'], how))
        for stat in src['stats']:
            info, warns = common.check_stat(stat, built[stat['id']])
            path = common.write_stat(stat['id'], built[stat['id']])
            cat[stat['id']] = catalogue_entry(stat, src, sources, info)
            # Content hash: the game appends it to the file's URL, so a
            # rebuilt file can never be served from a stale browser cache.
            cat[stat['id']]['hash'] = hashlib.sha1(open(path, 'rb').read()).hexdigest()[:12]
            flag = ('  ⚠ ' + '; '.join(warns)) if warns else ''
            print('  %-28s %6d pts  %s%s' % (stat['id'], info['points'],
                  ' '.join('%s %.1f%%' % (n[:2], 100 * s) for n, s in info['shares'].items()), flag))
            for c in dropped.get(stat['id'], []):
                print('    (dropped %s: %s)' % (c, gaps_for(stat['id'])[c]))
    json.dump(dict(sorted(cat.items())), open(CATALOGUE, 'w', encoding='utf-8'),
              indent=1, ensure_ascii=False)
    write_readme(cat, sources)
    print('catalogue: %d statistics → %s' % (len(cat), os.path.relpath(CATALOGUE, common.REPO)))


if __name__ == '__main__':
    try:
        main(sys.argv[1:])
    except BuildError as e:
        sys.exit('BUILD FAILED: %s' % e)
